--ConVar syncing
CreateConVar("ttt2_defective_inform_everyone", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_shop_order_prevention", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_detective_immunity", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_can_see_traitors", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_can_be_seen_by_traitors", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_can_see_defectives", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_corpse_reveal_mode", "0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_special_det_handling_mode", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_disable_spawn_if_no_detective", "1", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
CreateConVar("ttt2_defective_demote_detective_pct", "0.0", {FCVAR_ARCHIVE, FCVAR_NOTFIY, FCVAR_REPLICATED})
